### ISSUE TITLE
可以直接用canvas算圆点位置

### ISSUE THREAD

**Issue by ksky521** [WoeOm/you_jump_i_jump#9]
可以直接用canvas算圆点位置，还有小人的底部位置是最宽的，可以这样匹配出来小人的位置，这样就不用OpenCV那么复杂了，理论上是可以的~

**Comment by ksky521** [comment]
今天来看作者已经用OpenCV写了一些代码了，我的想法多此一举了，关掉

**Comment by WoeOm** [comment]
@ksky521 canvas 不清楚怎么实现 可以详细说下，正好学习一下

**Comment by ksky521** [comment]
@WoeOm 我今天晚上写个demo，等发到github在这里发给你~

**Comment by ksky521** [comment]
@WoeOm https://github.com/ksky521/wechat-jump-game-hack 看这个demo
